name: TMAS Scan
on:
  push:
    branches:
      - main

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TMAS CLI
        run: |
          curl -L https://example.com/path/to/trend_micro_installer.sh -o trend_micro_installer.sh
          chmod +x trend_micro_installer.sh
          sudo ./trend_micro_installer.sh


      - name: Scan Docker Image
        run: |
          export TMAS_API_KEY="${{ secrets.TMAS_API_KEY }}"
          tmas scan registry:bkimminich/juice-shop:latest --saveSBOM
