name: TMAS Scan

on:
  push:
    branches:
      - main

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TMAS CLI
        run: |
          curl -L https://tmas-cli-releases.s3.amazonaws.com/latest/tmas -o tmas
          chmod +x tmas
          export PATH="/path/to/tmas/binary/directory:$PATH"

      - name: Scan Docker Image
        run: |
          export TMAS_API_KEY="${{ secrets.TMAS_API_KEY }}"
          tmas scan registry:bkimminich/juice-shop:latest --saveSBOM
