name: TMAS Scan

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan with TMAS
        uses: trendmicro/tmas-scan-action@v1
        with:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}  # Your TMAS API key
          REGION: us-east-1  # Choose your desired region
          IMAGE: karan91052/juice-shop:latest  # Specify the image you want to scan
          SBOM: true  # Save SBOM to SBOM.json for later reference
          MALWARE_SCAN: true  # Enable malware scan
          MAX_TOTAL: 0  # Set acceptable maximum total vulnerabilities
          MAX_CRITICAL: 0  # Set acceptable maximum critical vulnerabilities
          MAX_HIGH: 0  # Set acceptable maximum high vulnerabilities
          MAX_MEDIUM: 0  # Set acceptable maximum medium vulnerabilities
          MAX_LOW: 0  # Set acceptable maximum low vulnerabilities
          MAX_NEGLIGIBLE: 0  # Set acceptable maximum negligible vulnerabilities
          MAX_UNKNOWN: 0  # Set acceptable maximum unknown vulnerabilities
          SCAN_RESULT_ARTIFACT: result.json  # Save scan result as an artifact

      - name: Upload Scan Result Artifact
        uses: actions/upload-artifact@v2
        with:
          name: scan-result
          path: result.json
