name: "TMAS Scan Action"
description: "Scan container images with Vision One Container Security"
author: "Trend Micro"
on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: TMAS Scan Action
        uses: trendmicro/tmas-scan-action@v1
        with:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}  # Your Vision One API key
          REGION: us-east-1  # Choose your desired region
          IMAGE: alpine  # The image to scan (public or accessible by the pipeline)
          SBOM: true  # Saves SBOM to SBOM.json so you can export it as an artifact later.
          MALWARE_SCAN: true  # Enable malware scan.
          MAX_TOTAL: 0
          MAX_CRITICAL: 0
          MAX_HIGH: 0
          MAX_MEDIUM: 0
          MAX_LOW: 0
          MAX_NEGLIGIBLE: 0
          MAX_UNKNOWN: 0
          SCAN_RESULT_ARTIFACT: result.json  # Save as an artifact in GitHub to keep the scan result.
          LOCAL_IMAGE_TARBALL: image.tar  # For pre-registry scanning (if applicable).

      # Optional: Upload scan result and SBOM as artifacts
      - name: 'Upload Scan Result Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: scan-result
          path: result.json
          retention-days: 30

      - name: 'Upload SBOM Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: SBOM.json
          retention-days: 30
