name: "TMAS Scan Action"
on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: TMAS Scan Action
        uses: trendmicro/tmas-scan-action@v1
        with:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
          IMAGE: alpine
          REGION: us-east-1
          SBOM: true
          MALWARE_SCAN: true
          MAX_TOTAL: 0
          MAX_CRITICAL: 0
          MAX_HIGH: 0
          MAX_MEDIUM: 0
          MAX_LOW: 0
          MAX_NEGLIGIBLE: 0
          MAX_UNKNOWN: 0
          SCAN_RESULT_ARTIFACT: result.json
          LOCAL_IMAGE_TARBALL: image.tar

      # Optional: Upload scan result and SBOM as artifacts
      - name: 'Upload Scan Result Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: scan-result
          path: result.json
          retention-days: 30

      - name: 'Upload SBOM Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: SBOM.json
          retention-days: 30
