name: Install and Scan with TMAS

on:
  push:
    branches:
      - main

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download TMAS installer script
        run: |
          curl -L https://example.com/path/to/trend_micro_installer.sh -o trend_micro_installer.sh
          chmod +x trend_micro_installer.sh

      - name: Verify TMAS installer script
        run: |
          cat trend_micro_installer.sh  # Display the script content for verification

      - name: Run TMAS installer
        run: |
          sudo ./trend_micro_installer.sh  # Run the installer script

      - name: Set TMAS_API_KEY environment variable
        run: echo "TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}" >> $GITHUB_ENV

      - name: Scan Docker Image
        run: |
          export TMAS_API_KEY="${{ secrets.TMAS_API_KEY }}"
          tmas scan registry:bkimminich/juice-shop:latest --saveSBOM
