name: TMAS Scan

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install TMAS CLI
        run: npm install -g @trendmicro/tmas-cli

      - name: Scan with TMAS
        run: tmas scan my-container-image:latest
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}  # Your TMAS API key

      - name: Upload Scan Result Artifact
        uses: actions/upload-artifact@v2
        with:
          name: scan-result
          path: tmas-report.json
