name: TMAS Scan Workflow

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: TMAS Scan Action
        uses: trendmicro/tmas-scan-action@v1
        with:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}  # Your Vision One API key
          REGION: us-east-1  # Choose your desired region
          IMAGE: alpine  # The image to scan (public or accessible by the pipeline)
          SBOM: true  # Save SBOM to SBOM.json
          MALWARE_SCAN: true  # Enable malware scan
          SCAN_RESULT_ARTIFACT: result.json  # Save scan result as an artifact
