name: TMAS Scan

on:
  push:
    branches:
      - main

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download TMAS CLI
        run: |
          curl -L https://tmas-cli-releases.s3.amazonaws.com/latest/tmas -o tmas
          

      - name: Scan Docker Image
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: |
          tmas scan --api-key "$TMAS_API_KEY" docker:karan91052/juice-shop:latest || exit 1
