name: TMAS Scan

on:
  push:
    branches:
      - main

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install TMAS CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
          sudo mv ./bin/trivy /usr/local/bin/trivy
          trivy --version


      - name: Verify TMAS CLI Installation
        run: |
          /usr/local/bin/tmas --version

      - name: Set TMAS_API_KEY environment variable
        run: echo "TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}" >> $GITHUB_ENV

      - name: Scan Docker Image
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: |
          /usr/local/bin/tmas scan --api-key "$TMAS_API_KEY" docker:karan91052/juice-shop:latest --saveSBOM || exit 1
