# .tmas-ci.yml

name: TMAS Scan

on:
  push:
    branches:
      - main

jobs:
  tmas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install TMAS CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
          sudo mv /usr/local/bin/trivy ./bin/trivy
          trivy --version

      - name: Verify TMAS CLI Installation
        run: |
          /usr/local/bin/trivy --version

      - name: Set TMAS_API_KEY environment variable
        run: echo "TMAS_API_KEY=${{ secrets.TMAS_API_KEY }}" >> $GITHUB_ENV

      - name: Scan Docker Image
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: |
          /usr/local/bin/trivy image --format json --output trivy-results.json karan91052/juice-shop:latest

      - name: Upload Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.json
